#!/usr/bin/python

from stats import *

#TOTALLY-RANDOM vs GNU
analyze_program(isWhite=False, komi=5, num_games=300,
  patterns='patterns.txt',
  bandit_coeff=0,
  amaf_coeff=2500,
  fill_board=1,
  long_game_coeff=3,
  cycles_mcts=30000,
  threads_mcts=5,
  limit_expansion=1,
  root_parallel=False,
  chinese_rules=True,
  rave=False,
  totally_random=True,
)

analyze_program(isWhite=True, komi=5, num_games=300,
  patterns='patterns.txt',
  bandit_coeff=0,
  amaf_coeff=2500,
  fill_board=1,
  long_game_coeff=3,
  cycles_mcts=30000,
  threads_mcts=5,
  limit_expansion=1,
  root_parallel=False,
  chinese_rules=True,
  rave=False,
  totally_random=True,
)

#RAVE-RANDOM vs GNU
analyze_program(isWhite=False, komi=5, num_games=300,
  patterns='patterns.txt',
  bandit_coeff=0,
  amaf_coeff=2500,
  fill_board=1,
  long_game_coeff=3,
  cycles_mcts=30000,
  threads_mcts=5,
  limit_expansion=1,
  root_parallel=False,
  chinese_rules=True,
  rave=True,
  totally_random=True,
)

analyze_program(isWhite=True, komi=5, num_games=300,
  patterns='patterns.txt',
  bandit_coeff=0,
  amaf_coeff=2500,
  fill_board=1,
  long_game_coeff=3,
  cycles_mcts=30000,
  threads_mcts=5,
  limit_expansion=1,
  root_parallel=False,
  chinese_rules=True,
  rave=True,
  totally_random=True,
)

#RAVE-KNOWLEDGE vs GNU
analyze_program(isWhite=False, komi=5, num_games=300,
  patterns='patterns.txt',
  bandit_coeff=0,
  amaf_coeff=2500,
  fill_board=1,
  long_game_coeff=3,
  cycles_mcts=30000,
  threads_mcts=5,
  limit_expansion=1,
  root_parallel=False,
  chinese_rules=True,
  rave=True,
  totally_random=False,
)

analyze_program(isWhite=True, komi=5, num_games=300,
  patterns='patterns.txt',
  bandit_coeff=0,
  amaf_coeff=2500,
  fill_board=1,
  long_game_coeff=3,
  cycles_mcts=30000,
  threads_mcts=5,
  limit_expansion=1,
  root_parallel=False,
  chinese_rules=True,
  rave=True,
  totally_random=False,
)

#SIMULATION STATS

analyze_program(isWhite=True, komi=5, num_games=300,
  patterns='patterns.txt',
  bandit_coeff=0,
  amaf_coeff=2500,
  fill_board=1,
  long_game_coeff=3,
  cycles_mcts=5000,
  threads_mcts=5,
  limit_expansion=1,
  root_parallel=False,
  chinese_rules=True,
  rave=True,
  totally_random=False,
)

analyze_program(isWhite=True, komi=5, num_games=300,
  patterns='patterns.txt',
  bandit_coeff=0,
  amaf_coeff=2500,
  fill_board=1,
  long_game_coeff=3,
  cycles_mcts=10000,
  threads_mcts=5,
  limit_expansion=1,
  root_parallel=False,
  chinese_rules=True,
  rave=True,
  totally_random=False,
)

analyze_program(isWhite=True, komi=5, num_games=300,
  patterns='patterns.txt',
  bandit_coeff=0,
  amaf_coeff=2500,
  fill_board=1,
  long_game_coeff=3,
  cycles_mcts=20000,
  threads_mcts=5,
  limit_expansion=1,
  root_parallel=False,
  chinese_rules=True,
  rave=True,
  totally_random=False,
)

analyze_program(isWhite=True, komi=5, num_games=300,
  patterns='patterns.txt',
  bandit_coeff=0,
  amaf_coeff=2500,
  fill_board=1,
  long_game_coeff=3,
  cycles_mcts=30000,
  threads_mcts=5,
  limit_expansion=1,
  root_parallel=False,
  chinese_rules=True,
  rave=True,
  totally_random=False,
)

analyze_program(isWhite=True, komi=5, num_games=300,
  patterns='patterns.txt',
  bandit_coeff=0,
  amaf_coeff=2500,
  fill_board=1,
  long_game_coeff=3,
  cycles_mcts=40000,
  threads_mcts=5,
  limit_expansion=1,
  root_parallel=False,
  chinese_rules=True,
  rave=True,
  totally_random=False,
)

analyze_program(isWhite=True, komi=5, num_games=300,
  patterns='patterns.txt',
  bandit_coeff=0,
  amaf_coeff=2500,
  fill_board=1,
  long_game_coeff=3,
  cycles_mcts=50000,
  threads_mcts=5,
  limit_expansion=1,
  root_parallel=False,
  chinese_rules=True,
  rave=True,
  totally_random=False,
)

analyze_program(isWhite=True, komi=5, num_games=300,
  patterns='patterns.txt',
  bandit_coeff=0,
  amaf_coeff=2500,
  fill_board=1,
  long_game_coeff=3,
  cycles_mcts=60000,
  threads_mcts=5,
  limit_expansion=1,
  root_parallel=False,
  chinese_rules=True,
  rave=True,
  totally_random=False,
)

analyze_program(isWhite=True, komi=5, num_games=300,
  patterns='patterns.txt',
  bandit_coeff=0,
  amaf_coeff=2500,
  fill_board=1,
  long_game_coeff=3,
  cycles_mcts=70000,
  threads_mcts=5,
  limit_expansion=1,
  root_parallel=False,
  chinese_rules=True,
  rave=True,
  totally_random=False,
)

