#!/bin/bash

WHITE="./bin/marcos_go \
    --patterns patterns.txt \
    --bandit_coeff 0 \
    --cycles_mcts 30000 \
    --amaf_coeff 2500 \
    --fill_board 1 \
    --limit_expansion 1 \
    --long_game_coeff 3 \
    --resign_limit 0.1 "

gogui -size 9 -program "$WHITE" -komi 5 -auto
